# Generated by Django 3.2.9 on 2021-11-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('P', 'Politics'), ('E', 'Entertainment'), ('T', 'Trending'), ('M', 'Music'), ('S', 'Sports')], default='T', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='newpost.jpg', upload_to='default_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_choices',
            field=models.CharField(choices=[('H', 'HOT'), ('N', 'NEW')], default='H', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
